
services:
  app:
    container_name: jobtestprep
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/code/app
    restart: unless-stopped
    develop:
      watch:
        - path: ./app
          target: /code/app
          action: sync
        - path: ./requirements.txt
          target: /code/requirements.txt
          action: rebuild
