
services:
  app:
    container_name: jobtestprep
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./src:/code/src
    restart: unless-stopped
    develop:
      watch:
        - path: ./src
          target: /code/src
          action: sync
        - path: ./requirements.txt
          target: /code/requirements.txt
          action: rebuild
